[package]
name = "rust-project-init"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "init"
path = "src/main.rs"

[[example]]
name = "hello"
path = "src/example/hello.rs"

[[example]]
name = "variable"
path = "src/example/variable.rs"

[[example]]
name = "val"
path = "src/example/val.rs"

[[example]]
name = "operation"
path = "src/example/operation.rs"

[[example]]
name = "derivation"
path = "src/example/derivation.rs"

[[example]]
name = "fibonacci"
path = "src/example/fibonacci.rs"

[[example]]
name = "if"
path = "src/example/if.rs"

[[example]]
name = "cycle"
path = "src/example/cycle.rs"

[[example]]
name = "breakOrContinue"
path = "src/example/breakOrContinue.rs"

[[example]]
name = "labels"
path = "src/example/labels.rs"

[[example]]
name = "scope"
path = "src/example/scope.rs"

[[example]]
name = "koraz"
path = "src/example/koraz.rs"

[[example]]
name = "fun"
path = "src/example/fun.rs"

[[example]]
name = "macro"
path = "src/example/macro.rs"

[[example]]
name = "arr"
path = "src/example/arr.rs"

[[example]]
name = "tup"
path = "src/example/tup.rs"

[[example]]
name = "arr_for"
path = "src/example/arr_for.rs"

[[example]]
name = "deconstruct"
path = "src/example/deconstruct.rs"

[[example]]
name = "nested"
path = "src/example/nested.rs"