[package]
name = "rust-project-init"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "variable"
path = "src/main.rs"

[[example]]
name = "hello"
path = "src/example/hello.rs"

[[example]]
name = "variable"
path = "src/example/variable.rs"

[[example]]
name = "val"
path = "src/example/val.rs"

[[example]]
name = "operation"
path = "src/example/operation.rs"